<?php

namespace AppBundle\Repository;

/**
 * NewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewRepository extends \Doctrine\ORM\EntityRepository
{
}
