AppBundle\Entity\Contact:
    type: entity
    table: contact
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        lastname:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: lastName
        email:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        mobile:
            type: string
            nullable: false
            length: 9
            options:
                fixed: false
        curso:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        observations:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
    lifecycleCallbacks: {  }
