AppBundle\Entity\Contact:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ContactRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '100'
        lastName:
            type: string
            length: '100'
        email:
            type: string
            length: '100'
        mobile:
            type: string
            length: '100'
        curso:
            type: string
            length: 255
        observations:
            type: text
    lifecycleCallbacks: {  }
