AppBundle\Entity\News:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\NewRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        description:
            type: text
        date:
            type: string
            length: 255
    lifecycleCallbacks: {  }
